## Regression

In [39]:
import numpy as np
import pandas as pd

In [40]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [41]:
def initialize_parameters(layer_dims):

    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):

        parameters['W'+ str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b'+ str(l)] = np.zeros((layer_dims[l],1))

    return parameters

In [42]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [43]:
def linear_forward(A_prev,W,b):

    Z = np.dot(W.T,A_prev)+b

    return Z

In [56]:
# Forward Prop
def L_layer_forward(X,parameters):

    A = X
    L = len(parameters)//2

    for l in range(1,L+1):
        A_prev = A
        W1 = parameters['W'+str(l)]
        b1 = parameters['b'+str(l)]
        # print('A'+str(l-1)+': ',A_prev)
        # print('W'+str(l)+': ',W1)
        # print('b'+str(l)+': ',b1)
        # print('--'*20)

        A = linear_forward(A_prev,W1,b1)
        # print('A'+str(l)+': ',A)
        # print('**'*20)

    return A,A_prev

In [45]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************

In [46]:
y_hat = y_hat[0][0]

In [47]:
A1

array([[1.6],
       [1.6]])

In [48]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [49]:
update_parameters(parameters,y,y_hat,A1,X)

In [50]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [51]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************

In [52]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.81270598]
 [1.81270598]]
****************************************
A1:  [[1.81270598]
 [1.81270598]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.52437005]]
****************************************

In [57]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729625
Epoch -  4 Loss -  3.252093863403161
Epoch -  5 Loss -  1.3407132589299964

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [58]:
# Using Keras
df.head()

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [62]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [65]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [66]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [68]:
model.get_weights()

[array([[ 0.6602981 ,  0.06573606],
        [-1.0936942 , -0.88592046]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.58981043],
        [-0.65541416]], dtype=float32),
 array([0.], dtype=float32)]

In [73]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [74]:
model.set_weights(new_weights)

In [75]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [79]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [80]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 27.9037
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.5852
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2451
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.9065
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.5697
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.2189
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.8474
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.4748
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.0807
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24.6455
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.2627
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.8477
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.4160
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 22.9383
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.5146
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.0312
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.5412
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21.0812
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 20.6173
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 20.1077
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19.5806
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.0546
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 18.5496
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 18.0549
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 17.5071
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16.9964
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16.5285
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15.9202
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15.4333
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 14.9168
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.3864
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.8314
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.3601
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.7898
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.3404
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.8386
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.3070
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.8126
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.3589
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.8888
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.4372
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.9490
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 8.5290
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.1420
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6948
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2935
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9696
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 6.5841
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 6.1685
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.8730
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5314
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.1762
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.8800
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.6654
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.3832
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0750
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.8624
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.6393
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.4128
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.1954
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.0080
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8860
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.6668
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.5655
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.3962
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.2426
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.1512
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.0637
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.9499
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.8295
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.7436
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.6768
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.6133
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.5554
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.4969

In [81]:
model.get_weights()

[array([[0.37347013, 0.37347013],
        [0.36542344, 0.36542344]], dtype=float32),
 array([0.27215868, 0.27215868], dtype=float32),
 array([[0.3727533],
        [0.3727533]], dtype=float32),
 array([0.20457725], dtype=float32)]

# Classification

In [82]:
import numpy as np
import pandas as pd

In [83]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [84]:
df.head()

   cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [85]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [86]:
# Utility Functions
def sigmoid(Z):
  
  A = 1/(1+np.exp(-Z))

  return A

In [87]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b

  A = sigmoid(Z)
  
  return A

In [88]:
# L-layer feed forward

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev

In [89]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [90]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.613402628898913

{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [91]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.568725622654268

{'W1': array([[0.10000937, 0.10001059],
        [0.10000937, 0.10001059]]),
 'b1': array([[1.24770113e-06],
        [1.24770113e-06]]),
 'W2': array([[0.10007424],
        [0.10007424]]),
 'b2': array([[0.10011761]])}

In [92]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.8353333695154365

{'W1': array([[0.10000463, 0.10000267],
        [0.10000463, 0.10000267]]),
 'b1': array([[4.56125378e-07],
        [4.56135584e-07]]),
 'W2': array([[0.10002712],
        [0.10002712]]),
 'b2': array([[0.09997049]])}

In [93]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.8238180133031612

{'W1': array([[0.09999911, 0.09999716],
        [0.09999911, 0.09999716]]),
 'b1': array([[-6.47175329e-07],
        [-6.47175081e-07]]),
 'W2': array([[0.09998609],
        [0.09998609]]),
 'b2': array([[0.09992997]])}

In [94]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7103199085929446
Epoch -  2 Loss -  0.6991702892802629
Epoch -  3 Loss -  0.6991679314811485
Epoch -  4 Loss -  0.6991655746710999
Epoch -  5 Loss -  0.6991632188496667
Epoch -  6 Loss -  0.699160864016399
Epoch -  7 Loss -  0.6991585101708473
Epoch -  8 Loss -  0.6991561573125619
Epoch -  9 Loss -  0.6991538054410936
Epoch -  10 Loss -  0.6991514545559935
Epoch -  11 Loss -  0.6991491046568126
Epoch -  12 Loss -  0.6991467557431024
Epoch -  13 Loss -  0.6991444078144144
Epoch -  14 Loss -  0.6991420608703007
Epoch -  15 Loss -  0.6991397149103133
Epoch -  16 Loss -  0.6991373699340042
Epoch -  17 Loss -  0.6991350259409265
Epoch -  18 Loss -  0.6991326829306324
Epoch -  19 Loss -  0.6991303409026751
Epoch -  20 Loss -  0.699127999856608
Epoch -  21 Loss -  0.6991256597919842
Epoch -  22 Loss -  0.6991233207083575
Epoch -  23 Loss -  0.6991209826052818
Epoch -  24 Loss -  0.699118645482311
Epoch -  25 Loss -  0.6991163093389996
Epoch -  26 Loss -  0.699113974174902
Epoch -  27 Loss -  0.6991116399895729
Epoch -  28 Loss -  0.6991093067825676
Epoch -  29 Loss -  0.699106974553441
Epoch -  30 Loss -  0.6991046433017485
Epoch -  31 Loss -  0.6991023130270458
Epoch -  32 Loss -  0.699099983728889
Epoch -  33 Loss -  0.6990976554068338
Epoch -  34 Loss -  0.6990953280604367
Epoch -  35 Loss -  0.6990930016892543
Epoch -  36 Loss -  0.6990906762928432
Epoch -  37 Loss -  0.6990883518707602
Epoch -  38 Loss -  0.699086028422563
Epoch -  39 Loss -  0.6990837059478086
Epoch -  40 Loss -  0.6990813844460546
Epoch -  41 Loss -  0.699079063916859
Epoch -  42 Loss -  0.6990767443597797
Epoch -  43 Loss -  0.6990744257743753
Epoch -  44 Loss -  0.699072108160204
Epoch -  45 Loss -  0.6990697915168249
Epoch -  46 Loss -  0.6990674758437966
Epoch -  47 Loss -  0.6990651611406782
Epoch -  48 Loss -  0.6990628474070294
Epoch -  49 Loss -  0.6990605346424095
Epoch -  50 Loss -  0.6990582228463785

{'W1': array([[0.09994267, 0.09984548],
        [0.09994272, 0.09984548]]),
 'b1': array([[-3.38405750e-05],
        [-3.38419977e-05]]),
 'W2': array([[0.09920806],
        [0.09920816]]),
 'b2': array([[0.09915209]])}

In [95]:
# Using Keras
model = Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

C:\Users\surya\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [96]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [97]:
model.get_weights()

[array([[ 0.6179832 ,  0.67064726],
        [-0.1571163 ,  0.94689167]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.91442573],
        [ 0.47383952]], dtype=float32),
 array([0.], dtype=float32)]

In [98]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [99]:
model.set_weights(new_weights)

In [100]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [101]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [103]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6945
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6943
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6941
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6940
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6943
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6939
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6939
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6941
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6939
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6939
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6938
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6938
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6937
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6939
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6937
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6937
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6938
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6936
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6936
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6936
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6936
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6935
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6935
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6935
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6935
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6935
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6937
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6934
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6936
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6933
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6934
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6933
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6933
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6933
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6934
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6933
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6933
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6933
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6932
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6932
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6931
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6932
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6932
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6932
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6931
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6932
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6930
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6931
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6931
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6931
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6930
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6931
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6930
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6930
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6930
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6930
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6930
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6930
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6929
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6930
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6931
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6928
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6929
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6928
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6929
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6929
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6930
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6929
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6928
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6927
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6927
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6927
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6928
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6927
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6927

In [104]:
model.get_weights()

[array([[0.10273187, 0.10273187],
        [0.08110889, 0.08110889]], dtype=float32),
 array([-0.04403997, -0.04403997], dtype=float32),
 array([[0.08967123],
        [0.08967123]], dtype=float32),
 array([-0.01988411], dtype=float32)]